constants_dictionary = {}
amino_acids = {}
molecule_tests = {}

constants_dictionary["Gravitational constant"] = 6.67430*(10**-11)
constants_dictionary["Speed of light"] = 3*(10**8)
constants_dictionary["Magnetic constant"] = 1.25663706*(10**-6)
constants_dictionary["Electric constant"] = 8.8541878*(10**-12)
constants_dictionary["Characteristic impedance of vacuum"] = 376.7303135
constants_dictionary["Planck constant"] = 6.62607*(10**-34)
constants_dictionary["Planck mass"] = 2.17647*(10**-8)
constants_dictionary["Planck length"] = 1.616229*(1-**-35)
constants_dictionary["Planck time"] = 5.39116*(10**-44)

constants_dictionary["Elementary charge"] = 1.6021766*(10**-19)
constants_dictionary["Magnetic flux quantum"] = 2.0678338*(10**-15)
constants_dictionary["Conductance quantum"] = 7.74809173*(10**-5)
constants_dictionary["Josephson constant"] = 4.83597852*(10**14)
constants_dictionary["von Klitzing constant"] = 25812.80746
constants_dictionary["Bohr magneton"] = 9.2740099*(10**-24)
constants_dictionary["Nuclear magneton"] = 5.0507836*(10**-27)

constants_dictionary["Fine-structure constant"] = 7.29735256*(10**-3)
constants_dictionary["Rydberg constant"] = 10973731.57
constants_dictionary["Bohr radius"] = 5.2917721*(10**-11)
constants_dictionary["Electron mass"] = 9.1093835*(10**-31)
constants_dictionary["Electron magnetic moment"] = -9.284764*(10**-24)
constants_dictionary["Muon mass"] = 1.8835315*(10**-28)
constants_dictionary["Muon magnetic moment"] = -4.490448*(10**-26)
constants_dictionary["Tau mass"] = 3.16747*(10**-27)
constants_dictionary["Proton mass"] = 1.6726218*(10**-27)
constants_dictionary["Proton magnetic moment"] = 1.4106067*(10**-26)
constants_dictionary["Neutron mass"] = 1.6749274*(10**-27)
constants_dictionary["Neutron magnetic moment"] = -9.662365*(10**-27)

constants_dictionary["Avogrado constant"] = 6.022*(10**23)
constants_dictionary["Atomic mass"] = 1.660539*(10**-27)
constants_dictionary["Faraday constant"] = 96485.33289
constants_dictionary["Molar gas constant"] = 8.3144598
constants_dictionary["Volume of one mole in room temp and pressure, in dm^3"] = 24
constants_dictionary["Boltzmann constant"] = 1.3806485
constants_dictionary["Molar volume of ideal gas"] = 0.022710947
constants_dictionary["Stefan-Boltzmann"] = 5.670367*(10**-8)

molecule_tests["Emulsion test"] = "Used to test for lipids. The sample is suspended in ethanol the decanted into water. If solution turns cloudy, lipids are present."
molecule_tests["Starch test"] = "Use drops of iodine on leaf after diluting iodine with water. If starch is present, it should turn blue-black."
molecule_tests["Benedict test"] = "Used to test for sugars. Sample mixed with Benedict's reagent and then boiled for 3-5 minutes. Forms a precipitate with colour Blue if sugar isn't present and Green-Red if it is, sugar concentration lowest at green and highest at red."
molecule_tests["Biuret test"] = "Used to test for protein. Sample mixed with copper sulfate. Protein present if blue precipitate formed."
molecule_tests["Test for hydrogen"] = "Makes flame in splint go out with a pop sound."
molecule_tests["Test for oxygen"] = "relights splint."
molecule_tests["Test for carbon dioxide"] = "Turns limewater cloudy."
molecule_tests["Test for chlorine"] = "Turns blue litmus paper into bleached white."
molecule_tests["Test for ammonia"] = "Turns red litmus paper blue."
molecule_tests["Test for halides"] = "Acid added and then Aqueous Silver Nitrate. A precipitate will be formed if halides are present: white for chloride, creamy for bromide, yellow for iodide"
molecule_tests["Tollen's test"] = "Aldehydes react with Tollen's reagent to form metallic silver, while ketones don't."
molecule_tests["Cation flame test"] = "Lilac for K+, red for Na+, green-blue for Cu+ and yellow for Ca+"
molecule_tests["Cation precipitate test"] = "Reacts with hydroxide to form precipitate. Cu2+: green, Cu+: red-orange, Na+: blue, Zn+ white and dissolves in excess, Ca+: white and doesn't dissolve in excess"
molecule_tests["Test for carbonates"] = "Reactc with nitric acid"
molecule_tests["Sulfate ions test"] = "First put nitric acid to remove carbonate ions. Then put Barium Chloride ions; if precipitate formed, sulfate ions are present"
molecule_tests["Alkene/alkane test"] = "Alkenes react with bromine (form colourless solution), alkanes don't (leave yellow solution)"
molecule_tests["Test for carboxylic acids"] = "Suddenly releases Carbon Dioxide after being mixed with Sodium Bicarbonate."
molecule_tests["Test for alcohols"] = "Suddenly releases hydrogen after being mixed with Sodium metal"
molecule_tests["Test for nitrogen"] = "Heat organic compound with sodium metal, acidify, then add iron(ii) sulfate. Prussian blue colour should be produced"
molecule_tests["Test for sulfur"] = "Heat organic compound with sodium metal, acidify, then sodium nitroprusside. Violet colour should be produced"

amino_acids["UUU"] = "Phenylalaline"
amino_acids["UUC"] = "Phenylalaline"
amino_acids["UUA"] = "Leucine"
amino_acids["UUG"] = "Leucine"
amino_acids["CUU"] = "Leucine"
amino_acids["CUC"] = "Leucine"
amino_acids["CUA"] = "Leucine"
amino_acids["CUG"] = "Leucine"
amino_acids["AUU"] = "Isoleucine"
amino_acids["AUC"] = "Isoleucine"
amino_acids["AUA"] = "Isoleucine"
amino_acids["AUG"] = "START"
amino_acids["GUU"] = "Valine"
amino_acids["GUC"] = "Valine"
amino_acids["GUA"] = "Valine"
amino_acids["GUG"] = "Valine"
amino_acids["UCU"] = "Serine"
amino_acids["UCC"] = "Serine"
amino_acids["UCA"] = "Serine"
amino_acids["UCG"] = "Serine"
amino_acids["CCU"] = "Proline"
amino_acids["CCC"] = "Proline"
amino_acids["CCA"] = "Proline"
amino_acids["CCG"] = "Proline"
amino_acids["ACU"] = "Threonine"
amino_acids["ACC"] = "Threonine"
amino_acids["ACA"] = "Threonine"
amino_acids["ACG"] = "Threonine"
amino_acids["GCU"] = "Alanine"
amino_acids["GCC"] = "Alanine"
amino_acids["GCA"] = "Alanine"
amino_acids["GCG"] = "Alanine"
amino_acids["UAU"] = ""
amino_acids["UAC"] = ""
amino_acids["UAA"] = ""
amino_acids["UAG"] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
amino_acids[""] = ""
